#include "userapp.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#include <time.h>

// the factorial function

int factorial(int n){
  
   int res=1;
   for(int i=2;i<=n;i++){
    res*=i;

   }
   return res;
}
// the effective done in each period consisting of multiple factorial computation
void do_job(int num){

 while(num--){

    factorial(100000000);
  }

}
//register function write register command into 
void REGISTER(pid_t PID,int Period,int ProcessTime){

   FILE *f=fopen("/proc/mp2/status","w");
   printf("The regitser  pid: %d, period:%dms, processtime:%dms\n",PID,Period,ProcessTime);
   fprintf(f, "R,%d,%d,%d", PID,Period,ProcessTime);
   fclose(f);

}
/*
 Read status function make sure the process is registerd correctly-->return 1

 else return 0;

*/
int READ_STATUS(pid_t PID){
  
   FILE *f=fopen("/proc/mp2/status","r");

   char buff[256];

   pid_t curr_pid;

   printf("checking the register pid\n");

   while(fgets(buff,256,f)){

     sscanf(buff,"%d%*s",&curr_pid);
   //find the pid
     if(curr_pid==PID){
            fclose(f);

            return 1;
      }

   }
  fclose(f);
  printf("PID: %d falied register\n",PID);
  return 0;

}

void YIELD(pid_t PID){

  FILE *f=fopen("/proc/mp2/status","w");
  printf("yield process pid is %d\n",PID);
  fprintf(f, "Y,%d", PID);
  fclose(f);

}//write yield command into module

void DEREGISTER( pid_t PID){

  FILE *f=fopen("/proc/mp2/status","w");
  printf("Deregister process id is %d\n",PID);
  fprintf(f, "D,%d", PID);
  fclose(f);

}
// get the currently user timer in micro seconds
unsigned long get_usec(){

  struct timeval time;

  while(gettimeofday(&time,NULL));

  return time.tv_sec*1000000+time.tv_usec;

}

// There should be two arguments  1.number_of_iteations 2. the iterations times in do_job which control the effective computation time 
int main(int argc, char* argv[])

{
  
   unsigned long t0,t1;

   int pid =getpid();

   int num=atoi(argv[2]); //number of loops in do_job which is proportional to co

   t0=get_usec();
  
   do_job(num);

   t1=get_usec();
  
   srand(time(NULL));

   int ProcessTime=(int)(t1-t0)/1000;//get the computation time in mile seconds

   int random=rand()%3+3; //get a random number in range(3,6)

   int Period= random*ProcessTime; //the period is generated by processtime* random number

   int num_iterations=atoi(argv[1]);// the number of period 

   printf("random number is %d\n", random);

   printf("The value of is %d,%d,%d",pid,Period, ProcessTime);

   REGISTER(pid,Period,ProcessTime);// register it

  //check whether it has been register successfully
  if(READ_STATUS(pid)==0){
              
        return 0;
   }

  YIELD(pid);// first time yield function 

  int n=0;
  
   while(num_iterations--){

     printf("pid : %d  get into %dth circle \n",pid,n);

     do_job(num);//do_job function 
    
     printf("pid: %d  finish the %dth circle\n", pid,n);

     YIELD(pid);//yield 

     n++;
     
    }
      
    DEREGISTER(pid);//Deregister here

    execlp("cat","cat","/proc/mp2/status",NULL);

    return 0;
}
